import { Vehicle, Booking, NotificationItem, ChatConversation, BlogPost } from '@/types';
import { EX_DRIVER } from './mockDriver';

// Mock Driver
export const MOCK_DRIVER = EX_DRIVER;

// Mock Vehicles
export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: 'vf7-premium',
    name: 'VinFast VF 7 Plus',
    brand: 'VinFast',
    licensePlate: '29A-789.99',
    color: 'Xanh Lá Xanh SM',
    seats: 5,
    pricePerKm: 15000,
    status: 'Sẵn sàng',
    image: 'vf7',
    description:
      'Dòng xe SUV điện phân khúc C cao cấp của VinFast. Sở hữu thiết kế vũ trụ phi thuyền cực kỳ cơ bắp, công suất 349 mã lực, 2 động cơ điện dẫn động 4 bánh toàn thời gian.',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'vf8-plus',
    name: 'VinFast VF 8 Plus',
    brand: 'VinFast',
    licensePlate: '30E-456.88',
    color: 'Trắng',
    seats: 5,
    pricePerKm: 18000,
    status: 'Sẵn sàng',
    image: 'vf8',
    description: 'SUV điện rộng rãi, phù hợp chuyến đi gia đình và hành lý nhiều.',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'vf9-eco',
    name: 'VinFast VF 9 Eco',
    brand: 'VinFast',
    licensePlate: '29B-222.77',
    color: 'Đen',
    seats: 7,
    pricePerKm: 22000,
    status: 'Sẵn sàng',
    image: 'vf9',
    description: 'Xe 7 chỗ cho nhóm đông người, không cần chọn ghế cụ thể.',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'vf6-busy',
    name: 'VinFast VF 6',
    brand: 'VinFast',
    licensePlate: '51F-909.12',
    color: 'Xanh dương',
    seats: 5,
    pricePerKm: 13000,
    status: 'Đang bận',
    image: 'vf6',
    description: 'Xe đô thị gọn gàng, hiện có lịch bận ở một số khung giờ.',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
];

// Mock Bookings
export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'BK-89021',
    customerId: 'customer_1',
    customerName: 'Nguyễn Minh Anh',
    customerPhone: '0912345678',
    customerEmail: 'minhanh@gmail.com',
    pickupLocation: 'Vinhomes Ocean Park, Gia Lâm, Hà Nội',
    dropoffLocation: 'Sân bay Quốc tế Nội Bài, Hà Nội',
    date: '2026-06-10',
    time: '08:00',
    passengers: 2,
    note: 'Xin vui lòng đi cổng chào khu Ruby đón em ạ.',
    vehicleId: 'vf7-premium',
    vehicle: MOCK_VEHICLES[0],
    driverId: 'driver_1',
    driverName: MOCK_DRIVER.name,
    driverPhone: MOCK_DRIVER.phone,
    estimatedPrice: 450000,
    distance: 30,
    createdAt: '2026-06-09T08:30:00Z',
    updatedAt: '2026-06-09T08:30:00Z',
    status: 'SEARCHING_DRIVER',
  },
  {
    id: 'BK-87211',
    customerId: 'customer_1',
    customerName: 'Trần Thị Mai',
    customerPhone: '0987654321',
    customerEmail: 'maitran@gmail.com',
    pickupLocation: 'Keangnam Landmark 72, Mễ Trì, Nam Từ Liêm, Hà Nội',
    dropoffLocation: 'Nhà hát Lớn Hà Nội, Tràng Tiền, Hoàn Kiếm',
    date: '2026-06-09',
    time: '14:30',
    passengers: 1,
    note: 'Đồ đạc gọn nhẹ không có hành lý ký gửi.',
    vehicleId: 'vf7-premium',
    vehicle: MOCK_VEHICLES[0],
    driverId: 'driver_1',
    driverName: MOCK_DRIVER.name,
    driverPhone: MOCK_DRIVER.phone,
    estimatedPrice: 150000,
    distance: 10,
    createdAt: '2026-06-08T10:15:00Z',
    updatedAt: '2026-06-08T10:15:00Z',
    status: 'DRIVER_ACCEPTED',
  },
  {
    id: 'BK-86392',
    customerId: 'customer_2',
    customerName: 'Lê Hoàng Nam',
    customerPhone: '0901122334',
    customerEmail: 'namle@gmail.com',
    pickupLocation: 'Bệnh viện Bạch Mai, Giải Phóng, Đống Đa, Hà Nội',
    dropoffLocation: 'Ga Hà Nội, Lê Duẩn, Hà Nội',
    date: '2026-06-05',
    time: '10:00',
    passengers: 3,
    note: 'Người lớn tuổi cần hỗ trợ lên xuống xe.',
    vehicleId: 'vf7-premium',
    vehicle: MOCK_VEHICLES[0],
    driverId: 'driver_1',
    driverName: MOCK_DRIVER.name,
    driverPhone: MOCK_DRIVER.phone,
    estimatedPrice: 750000,
    distance: 50,
    createdAt: '2026-06-04T12:00:00Z',
    updatedAt: '2026-06-04T12:00:00Z',
    status: 'TRIP_COMPLETED',
  },
  {
    id: 'BK-85123',
    customerId: 'customer_3',
    customerName: 'Phạm Minh Đức',
    customerPhone: '0944556677',
    customerEmail: 'ducpham@gmail.com',
    pickupLocation: 'Aeon Mall Hà Đông, Hà Nội',
    dropoffLocation: 'Công viên Thống Nhất, Hà Nội',
    date: '2026-06-01',
    time: '19:00',
    passengers: 4,
    note: 'Có em bé đi cùng.',
    vehicleId: 'vf7-premium',
    vehicle: MOCK_VEHICLES[0],
    driverId: 'driver_1',
    driverName: MOCK_DRIVER.name,
    driverPhone: MOCK_DRIVER.phone,
    estimatedPrice: 280000,
    distance: 18,
    createdAt: '2026-06-01T15:00:00Z',
    updatedAt: '2026-06-01T15:00:00Z',
    status: 'CUSTOMER_CANCELLED',
  },
];

// Mock Notifications
export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'nt-1',
    userId: 'customer_1',
    title: 'Đặt lịch xe thành công',
    content:
      'Yêu cầu đặt xe đi Sân bay Nội Bài (BK-89021) lúc 08:00 ngày 10/06 đã được gửi đến tài xế.',
    time: '02 phút trước',
    type: 'booking_success',
    read: false,
    relatedBookingId: 'BK-89021',
    createdAt: '2026-06-09T08:30:00Z',
  },
  {
    id: 'nt-2',
    userId: 'customer_1',
    title: 'Tài xế Nguyễn Xuân Đài đã xác nhận',
    content:
      'Chuyến đi Keangnam đến Nhà hát Lớn lúc 14:30 hôm nay đã được tài xế xác nhận. Vui lòng chuẩn bị di chuyển.',
    time: '1 giờ trước',
    type: 'driver_confirm',
    read: false,
    relatedBookingId: 'BK-87211',
    createdAt: '2026-06-09T07:30:00Z',
  },
  {
    id: 'nt-3',
    userId: 'customer_1',
    title: 'Chuyến đi hoàn thành',
    content:
      'Cảm ơn quý khách đã di chuyển cùng VinFast VF 7! Chuyến đi ngày 05/06 đã hoàn tất xuất sắc.',
    time: '4 ngày trước',
    type: 'trip_done',
    read: true,
    relatedBookingId: 'BK-86392',
    createdAt: '2026-06-05T12:00:00Z',
  },
];

// Mock Chat Conversations
export const MOCK_CONVERSATIONS: ChatConversation[] = [
  {
    id: 'conv-1',
    participantId: 'driver_1',
    participantName: MOCK_DRIVER.name,
    participantAvatar: MOCK_DRIVER.avatar,
    lastMessage: 'Okay, I will be there in 5 minutes',
    lastMessageTime: '2 phút trước',
    unreadCount: 1,
    messages: [
      {
        id: 'msg-1',
        sender: 'driver',
        senderName: MOCK_DRIVER.name,
        text: 'Xin chào quý khách! Tôi là tài xế Nguyễn Xuân Đài.',
        timestamp: '2026-06-09T14:20:00Z',
        read: true,
      },
      {
        id: 'msg-2',
        sender: 'user',
        senderName: 'Bạn',
        text: 'Chào anh! Anh đến được chưa?',
        timestamp: '2026-06-09T14:25:00Z',
        read: true,
      },
      {
        id: 'msg-3',
        sender: 'driver',
        senderName: MOCK_DRIVER.name,
        text: 'Okay, I will be there in 5 minutes',
        timestamp: '2026-06-09T14:28:00Z',
        read: false,
      },
    ],
  },
];

// Mock Blog Posts
export const MOCK_BLOG_POSTS: BlogPost[] = [
  {
    id: 'post-1',
    driverId: 'driver_1',
    driverName: MOCK_DRIVER.name,
    driverAvatar: MOCK_DRIVER.avatar,
    caption: 'Một ngày tuyệt vời trên đường Hà Nội với chiếc VF7 yêu thích!',
    mediaUrls: [
      'https://images.unsplash.com/photo-1532274040911-5f82f1d51c7d?auto=format&fit=crop&q=80&w=800',
    ],
    mediaTypes: ['image'],
    likes: 245,
    comments: 12,
    shares: 8,
    liked: false,
    createdAt: '2026-06-08T10:00:00Z',
    updatedAt: '2026-06-08T10:00:00Z',
  },
  {
    id: 'post-2',
    driverId: 'driver_1',
    driverName: MOCK_DRIVER.name,
    driverAvatar: MOCK_DRIVER.avatar,
    caption:
      'Cảnh đẹp hoàng hôn tại Sân bay Nội Bài. Mọi chuyến đi đều là một câu chuyện!',
    mediaUrls: [
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=800',
    ],
    mediaTypes: ['image'],
    likes: 189,
    comments: 8,
    shares: 5,
    liked: false,
    createdAt: '2026-06-07T16:00:00Z',
    updatedAt: '2026-06-07T16:00:00Z',
  },
];
